# Generated by Django 5.2.1 on 2025-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('author', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('PSQL', 'Postgres'), ('MSQL', 'Mysql'), ('SQLT', 'Sqlite'), ('MGDB', 'Mongodb'), ('CHRM', 'Chroma')])),
                ('dump', models.TextField(blank=True, default='')),
            ],
        ),
    ]
