# Generated by Django 5.2.2 on 2025-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='dump',
            field=models.TextField(blank=True, default=''),
        ),
    ]
