# Generated by Django 5.2.1 on 2025-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('PSQL', 'Postgres'), ('MSQL', 'Mysql'), ('SQLT', 'Sqlite'), ('MGDB', 'Mongodb'), ('CHRM', 'Chroma')]),
        ),
    ]
