# Generated by Django 5.2.2 on 2025-06-17 21:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbschema',
            old_name='sql_dump',
            new_name='schema_description',
        ),
        migrations.AddField(
            model_name='dbschema',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 6, 17, 21, 41, 21, 373369, tzinfo=datetime.timezone.utc)),
        ),
    ]
