@startuml sequence

Frontend ->  DjangoREST: Request Templates
DjangoREST -> DjangoORM: Get Templates
DjangoREST <-- DjangoORM: Return Templates
Frontend <-- DjangoREST: Return Templates

Frontend -> DjangoREST: Send DB Query
DjangoREST -> DBEngine: Execute DB Query
DBEngine -> DBConnector: Connect to DB and execute Query
DBEngine <-- DBConnector: Return result of executed query
DjangoREST <-- DBEngine: Return processed query result
Frontend <-- DjangoREST: Return valid JSON result query

Frontend -> DjangoREST: Save DB to Template
DjangoREST -> DBEngine: Request to save the Template

@enduml