# Generated by Django 5.2.1 on 2025-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='image',
            field=models.ImageField(blank=True, upload_to='classroom_images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, upload_to='article_images'),
        ),
    ]
