# Generated by Django 5.2.1 on 2025-07-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
    ]
