# Generated by Django 5.2.1 on 2025-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0004_alter_article_file_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='backend_db.article'),
        ),
    ]
