# Generated by Django 5.2.1 on 2025-07-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0005_alter_classroom_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_date',
        ),
    ]
