name: Quick Lint Check

on:
  push:
    paths:
      - 'backend/**/*.py'
  pull_request:
    paths:
      - 'backend/**/*.py'

jobs:
  quick-lint:
    runs-on: ubuntu-latest
    name: Quick Python Linting
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-import-order flake8-docstrings flake8-bugbear
        
    - name: Quick syntax check
      run: |
        # Check for syntax errors and undefined names
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Full lint check
      run: |
        # Run full linting suite
        flake8 backend/ --count --statistics --format=github
      continue-on-error: true
